name: jenkins
services:
  server:
    image: jenkins/jenkins:latest
    container_name: jenkins-server
    hostname: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - 50000:50000
      - 172.17.0.1:59055:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/srv/$USER/docker/jenkins/jenkins/latest/rootfs/data/jenkins:/var/jenkins_home
    networks:
      - jenkins

networks:
  jenkins:
    name: jenkins
    external: false
